# Generated by Django 3.0 on 2020-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
