# Generated by Django 3.0 on 2020-04-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0002_gym_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gym',
            new_name='GymLocation',
        ),
    ]
