# Generated by Django 3.0 on 2020-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0003_auto_20200429_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='ability',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
