# Generated by Django 3.0 on 2020-04-29 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0004_gymlocation_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
