# Generated by Django 3.0 on 2020-04-29 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0006_auto_20200429_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='my_date_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
