# Generated by Django 3.0 on 2020-05-01 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0008_remove_gymlocation_my_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='my_date_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
