# Generated by Django 3.0 on 2020-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0010_remove_gymlocation_my_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
