# Generated by Django 3.0 on 2020-05-06 14:31

from django.db import migrations, models
import mmm.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0011_gymlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymlocation',
            name='ability',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[mmm.validators.validate_ability]),
        ),
    ]
