# Generated by Django 3.0 on 2020-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0013_gymlocation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlocation',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
