# Generated by Django 3.0 on 2020-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0014_gymlocation_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymlocation',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AlterField(
            model_name='gymlocation',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
