# Generated by Django 3.0 on 2020-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0017_auto_20200624_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymlocation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
