# Generated by Django 3.0 on 2020-06-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200606_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
    ]
