# Generated by Django 3.0 on 2020-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nickname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
