# Generated by Django 3.0 on 2020-05-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_item_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Female',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Male',
            field=models.BooleanField(default=True),
        ),
    ]
