# Generated by Django 3.0 on 2020-05-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20200525_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Female',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='Male',
            field=models.BooleanField(default=False),
        ),
    ]
