# Generated by Django 3.0 on 2020-05-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20200525_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Female',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Male',
        ),
    ]
