# Generated by Django 3.0 on 2020-06-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20200525_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
